INSERT INTO EuropeTerritories VALUES("AD", "Andorra")
INSERT INTO EuropeTerritories VALUES("AL", "Albania")
INSERT INTO EuropeTerritories VALUES("AM", "Armenia")
INSERT INTO EuropeTerritories VALUES("AT", "Austria")
INSERT INTO EuropeTerritories VALUES("AX", "Aland Islands")
INSERT INTO EuropeTerritories VALUES("AZ", "Azerbaijan")
INSERT INTO EuropeTerritories VALUES("BA", "Bosnia and Herzegovina")
INSERT INTO EuropeTerritories VALUES("BE", "Belgium")
INSERT INTO EuropeTerritories VALUES("BG", "Bulgaria")
INSERT INTO EuropeTerritories VALUES("BY", "Belarus")
INSERT INTO EuropeTerritories VALUES("CH", "Switzerland")
INSERT INTO EuropeTerritories VALUES("CS", "Former Serbia and Montenegro")
INSERT INTO EuropeTerritories VALUES("CY", "Cyprus")
INSERT INTO EuropeTerritories VALUES("CZ", "Czech Republic")
INSERT INTO EuropeTerritories VALUES("DD", "Former East Germany")
INSERT INTO EuropeTerritories VALUES("DE", "Germany")
INSERT INTO EuropeTerritories VALUES("DK", "Denmark")
INSERT INTO EuropeTerritories VALUES("EE", "Estonia")
INSERT INTO EuropeTerritories VALUES("ES", "Spain")
INSERT INTO EuropeTerritories VALUES("FI", "Finland")
INSERT INTO EuropeTerritories VALUES("FO", "Faroe Islands")
INSERT INTO EuropeTerritories VALUES("FR", "France")
INSERT INTO EuropeTerritories VALUES("GB", "United Kingdom of Great Britain and Northern Ireland")
INSERT INTO EuropeTerritories VALUES("GE", "Georgia")
INSERT INTO EuropeTerritories VALUES("GG", "Guernsey")
INSERT INTO EuropeTerritories VALUES("GI", "Gibraltar")
INSERT INTO EuropeTerritories VALUES("GR", "Greece")
INSERT INTO EuropeTerritories VALUES("HR", "Croatia")
INSERT INTO EuropeTerritories VALUES("HU", "Hungary")
INSERT INTO EuropeTerritories VALUES("IE", "Ireland")
INSERT INTO EuropeTerritories VALUES("IM", "Isle of Man")
INSERT INTO EuropeTerritories VALUES("IS", "Iceland")
INSERT INTO EuropeTerritories VALUES("IT", "Italy")
INSERT INTO EuropeTerritories VALUES("JE", "Jersey")
INSERT INTO EuropeTerritories VALUES("LI", "Liechtenstein")
INSERT INTO EuropeTerritories VALUES("LT", "Lithuania")
INSERT INTO EuropeTerritories VALUES("LU", "Luxembourg")
INSERT INTO EuropeTerritories VALUES("LV", "Latvia")
INSERT INTO EuropeTerritories VALUES("MC", "Monaco")
INSERT INTO EuropeTerritories VALUES("MD", "Republic of Moldova")
INSERT INTO EuropeTerritories VALUES("ME", "Montenegro")
INSERT INTO EuropeTerritories VALUES("MT", "Malta")
INSERT INTO EuropeTerritories VALUES("NL", "Netherlands")
INSERT INTO EuropeTerritories VALUES("NO", "Norway")
INSERT INTO EuropeTerritories VALUES("PL", "Poland")
INSERT INTO EuropeTerritories VALUES("PT", "Portugal")
INSERT INTO EuropeTerritories VALUES("RO", "Romania")
INSERT INTO EuropeTerritories VALUES("RS", "Serbia")
INSERT INTO EuropeTerritories VALUES("RU", "Russian Federation")
INSERT INTO EuropeTerritories VALUES("SE", "Sweden")
INSERT INTO EuropeTerritories VALUES("SI", "Slovenia")
INSERT INTO EuropeTerritories VALUES("SK", "Slovakia")
INSERT INTO EuropeTerritories VALUES("SM", "San Marino")
INSERT INTO EuropeTerritories VALUES("SU", "Former Soviet Union")
INSERT INTO EuropeTerritories VALUES("TR", "Turkey")
INSERT INTO EuropeTerritories VALUES("UA", "Ukraine")
INSERT INTO EuropeTerritories VALUES("VA", "Holy See")
INSERT INTO EuropeTerritories VALUES("XE", "Europe")
INSERT INTO EuropeTerritories VALUES("YU", "Former Yugoslavia")
INSERT INTO EuropeTerritories VALUES("ZC", "Former Czechoslovakia")